# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
#      args:
#        ARG: <ARG>
    image: ift6758/serving:latest
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - 8501:8501
    environment:
      BACKEND_URL: "serving"
    depends_on:
      - serving

     
